/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/blastoise.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/blastoise.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes['pm0009_00_01_(merge)']} />
          <group name="Body">
            <skinnedMesh name="BodySkin" geometry={nodes.BodySkin.geometry} material={materials.BodyA} skeleton={nodes.BodySkin.skeleton} />
            <skinnedMesh name="BodySkin_1" geometry={nodes.BodySkin_1.geometry} material={materials.BodyB} skeleton={nodes.BodySkin_1.skeleton} />
            <skinnedMesh name="BodySkin_2" geometry={nodes.BodySkin_2.geometry} material={materials.Eyes} skeleton={nodes.BodySkin_2.skeleton} />
          </group>
          <skinnedMesh name="Cannon" geometry={nodes.Cannon.geometry} material={materials.BodyB} skeleton={nodes.Cannon.skeleton} />
          <skinnedMesh name="Cover" geometry={nodes.Cover.geometry} material={materials.BodyB} skeleton={nodes.Cover.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/blastoise.glb')
