/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/bulbasaur.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/bulbasaur.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes['pm0001_00_01_(merge)']} />
          <group name="Body">
            <skinnedMesh name="pm0001_00_00_BodySkin" geometry={nodes.pm0001_00_00_BodySkin.geometry} material={materials.BodyB} skeleton={nodes.pm0001_00_00_BodySkin.skeleton} />
            <skinnedMesh name="pm0001_00_00_BodySkin_1" geometry={nodes.pm0001_00_00_BodySkin_1.geometry} material={materials.BodyA} skeleton={nodes.pm0001_00_00_BodySkin_1.skeleton} />
            <skinnedMesh name="pm0001_00_00_BodySkin_2" geometry={nodes.pm0001_00_00_BodySkin_2.geometry} material={materials.Eyes} skeleton={nodes.pm0001_00_00_BodySkin_2.skeleton} />
          </group>
          <skinnedMesh name="WhipL" geometry={nodes.WhipL.geometry} material={materials.BodyB} skeleton={nodes.WhipL.skeleton} />
          <skinnedMesh name="WhipR" geometry={nodes.WhipR.geometry} material={materials.BodyB} skeleton={nodes.WhipR.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bulbasaur.glb')
