/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/charmander.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/charmander.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes['pm0004_00_01_(merge)']} />
          <group name="Body">
            <skinnedMesh name="pm0004_00_00_Skin" geometry={nodes.pm0004_00_00_Skin.geometry} material={materials.BodyA} skeleton={nodes.pm0004_00_00_Skin.skeleton} />
            <skinnedMesh name="pm0004_00_00_Skin_1" geometry={nodes.pm0004_00_00_Skin_1.geometry} material={materials.Eyes} skeleton={nodes.pm0004_00_00_Skin_1.skeleton} />
          </group>
          <skinnedMesh name="FireCore" geometry={nodes.FireCore.geometry} material={materials.FireM} skeleton={nodes.FireCore.skeleton} />
          <skinnedMesh name="FireMask1" geometry={nodes.FireMask1.geometry} material={materials.Fire1} skeleton={nodes.FireMask1.skeleton} />
          <skinnedMesh name="FireMask2" geometry={nodes.FireMask2.geometry} material={materials.Fire2} skeleton={nodes.FireMask2.skeleton} />
          <skinnedMesh name="FireMask3" geometry={nodes.FireMask3.geometry} material={materials.Fire3} skeleton={nodes.FireMask3.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/charmander.glb')
