/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/ivysaur.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/ivysaur.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="attack01">
        <group name="Ivysaur" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.pm0002_00_00} />
          <skinnedMesh name="body" geometry={nodes.body.geometry} material={materials.BodyA} skeleton={nodes.body.skeleton} />
          <skinnedMesh name="eye" geometry={nodes.eye.geometry} material={materials.Eyes} skeleton={nodes.eye.skeleton} />
          <group name="flower">
            <skinnedMesh name="pm0002_00_00_flower_mesh_shape" geometry={nodes.pm0002_00_00_flower_mesh_shape.geometry} material={materials.BodyB} skeleton={nodes.pm0002_00_00_flower_mesh_shape.skeleton} />
            <skinnedMesh name="pm0002_00_00_flower_mesh_shape_1" geometry={nodes.pm0002_00_00_flower_mesh_shape_1.geometry} material={materials.BodyC} skeleton={nodes.pm0002_00_00_flower_mesh_shape_1.skeleton} />
          </group>
          <skinnedMesh name="leaf" geometry={nodes.leaf.geometry} material={materials.BodyB} skeleton={nodes.leaf.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ivysaur.glb')
