/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/squirtle.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/squirtle.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="attack01tranm">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes.pm0007_00_00} />
          <group name="body">
            <skinnedMesh name="pm0007_00_00_body_mesh_shape" geometry={nodes.pm0007_00_00_body_mesh_shape.geometry} material={materials.BodyA} skeleton={nodes.pm0007_00_00_body_mesh_shape.skeleton} />
            <skinnedMesh name="pm0007_00_00_body_mesh_shape_1" geometry={nodes.pm0007_00_00_body_mesh_shape_1.geometry} material={materials.BodyB} skeleton={nodes.pm0007_00_00_body_mesh_shape_1.skeleton} />
          </group>
          <skinnedMesh name="eye" geometry={nodes.eye.geometry} material={materials.Eyes} skeleton={nodes.eye.skeleton} />
          <skinnedMesh name="shell" geometry={nodes.shell.geometry} material={materials.BodyB} skeleton={nodes.shell.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/squirtle.glb')
