/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/venusaur.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/venusaur.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes['pm0003_01_01_(merge)']} />
          <group name="Body1">
            <skinnedMesh name="pm0003_00_00_BodySkin" geometry={nodes.pm0003_00_00_BodySkin.geometry} material={materials.BodyA} skeleton={nodes.pm0003_00_00_BodySkin.skeleton} />
            <skinnedMesh name="pm0003_00_00_BodySkin_1" geometry={nodes.pm0003_00_00_BodySkin_1.geometry} material={materials.Eyes} skeleton={nodes.pm0003_00_00_BodySkin_1.skeleton} />
          </group>
          <group name="Body2">
            <skinnedMesh name="pm0003_00_00_FlowerSkin" geometry={nodes.pm0003_00_00_FlowerSkin.geometry} material={materials.BodyB} skeleton={nodes.pm0003_00_00_FlowerSkin.skeleton} />
            <skinnedMesh name="pm0003_00_00_FlowerSkin_1" geometry={nodes.pm0003_00_00_FlowerSkin_1.geometry} material={materials.BodyC} skeleton={nodes.pm0003_00_00_FlowerSkin_1.skeleton} />
          </group>
          <skinnedMesh name="Flower" geometry={nodes.Flower.geometry} material={materials.BodyB} skeleton={nodes.Flower.skeleton} />
          <skinnedMesh name="Leaf" geometry={nodes.Leaf.geometry} material={materials.BodyB} skeleton={nodes.Leaf.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/venusaur.glb')
