/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/ubuntu/DevForge/pokemon-prop-hunt/public/models/wartortle.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/wartortle.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes['pm0008_00_01_(merge)']} />
          <group name="Body">
            <skinnedMesh name="pm0008_00_00_BodySkin" geometry={nodes.pm0008_00_00_BodySkin.geometry} material={materials.BodyA} skeleton={nodes.pm0008_00_00_BodySkin.skeleton} />
            <skinnedMesh name="pm0008_00_00_BodySkin_1" geometry={nodes.pm0008_00_00_BodySkin_1.geometry} material={materials.Eyes} skeleton={nodes.pm0008_00_00_BodySkin_1.skeleton} />
          </group>
          <skinnedMesh name="Skin" geometry={nodes.Skin.geometry} material={materials.BodyA} skeleton={nodes.Skin.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wartortle.glb')
